INFO     root:test_api_all.py:83 修改无效身份，修改失败是否自动化： YES
INFO     root:test_api_all.py:171 ********正在执行 修改无效身份，修改失败**********
INFO     root:test_api_all.py:204 请求方法PUT，
请求头{'content-type': 'application/json', 'Authorization': 'bearer e983dcb9-7966-4193-8622-a35615e5a3db'},
请求接口https://bss-api.haoshitong.com/api/customer/users/7447301
INFO     root:test_api_all.py:205 请求参数:
{"areaCode":"+86","departmentId":"570367","type":1,"userName":"13807981437","password":"123456","displayName":"修改手机号","userLevel":5,"status":1},
请求文件:None
DEBUG    urllib3.connectionpool:connectionpool.py:959 Starting new HTTPS connection (1): bss-api.haoshitong.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:437 https://bss-api.haoshitong.com:443 "PUT /api/customer/users/7447301 HTTP/1.1" 200 None
INFO     root:test_api_all.py:210 返回{"resCode":20021,"resMessage":"The userlevel not exist"}