DEBUG    urllib3.connectionpool:connectionpool.py:959 Starting new HTTPS connection (1): oauth.haoshitong.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:437 https://oauth.haoshitong.com:443 "POST /oauth2/token HTTP/1.1" 200 None
INFO     root:test_api_all.py:283 删除大陆手机的数据是否自动化： YES
INFO     root:test_api_all.py:286 连接ssh 120.24.43.28 host 127.0.0.1, 执行sql语句: 
  DELETE t_roominfo,t_apiservice,t_userinfo,t_department,t_businessinfo,t_user_binding_info FROM t_userinfo
        left join t_user_binding_info ON t_user_binding_info.userId = t_userinfo.UserID 
  left join t_businessinfo on t_userinfo.CompanyId=t_businessinfo.ID
  left join t_department on t_businessinfo.ID=t_department.CompanyId
  left join t_roominfo on t_businessinfo.ID=t_roominfo.CompanyId
  left join t_apiservice on t_roominfo.CompanyId=t_apiservice.BusinessID
WHERE
     UserName='13008887741';......
DEBUG    paramiko.transport:transport.py:1819 starting thread (client mode): 0x136a3730
DEBUG    paramiko.transport:transport.py:1819 Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG    paramiko.transport:transport.py:1819 Remote version/idstring: SSH-2.0-OpenSSH_5.3
INFO     paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_5.3)
DEBUG    paramiko.transport:transport.py:1819 kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG    paramiko.transport:transport.py:1819 Kex agreed: diffie-hellman-group-exchange-sha256
DEBUG    paramiko.transport:transport.py:1819 HostKey agreed: ssh-rsa
DEBUG    paramiko.transport:transport.py:1819 Cipher agreed: aes128-ctr
DEBUG    paramiko.transport:transport.py:1819 MAC agreed: hmac-sha2-256
DEBUG    paramiko.transport:transport.py:1819 Compression agreed: none
DEBUG    paramiko.transport:transport.py:1819 Got server p (2048 bits)
DEBUG    paramiko.transport:transport.py:1819 kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
DEBUG    paramiko.transport:transport.py:1819 Switch to new keys ...
DEBUG    paramiko.transport:transport.py:1819 Attempting public-key auth...
DEBUG    paramiko.transport:transport.py:1819 userauth is OK
INFO     paramiko.transport:transport.py:1819 Authentication (publickey) failed.
DEBUG    paramiko.transport:transport.py:1819 EOF in transport thread
DEBUG    paramiko.transport:transport.py:1819 starting thread (client mode): 0x136a3cf0
DEBUG    paramiko.transport:transport.py:1819 Local version/idstring: SSH-2.0-paramiko_2.7.2
DEBUG    paramiko.transport:transport.py:1819 Remote version/idstring: SSH-2.0-OpenSSH_5.3
INFO     paramiko.transport:transport.py:1819 Connected (version 2.0, client OpenSSH_5.3)
DEBUG    paramiko.transport:transport.py:1819 kex algos:['diffie-hellman-group-exchange-sha256', 'diffie-hellman-group-exchange-sha1', 'diffie-hellman-group14-sha1', 'diffie-hellman-group1-sha1'] server key:['ssh-rsa', 'ssh-dss'] client encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] server encrypt:['aes128-ctr', 'aes192-ctr', 'aes256-ctr', 'arcfour256', 'arcfour128', 'aes128-cbc', '3des-cbc', 'blowfish-cbc', 'cast128-cbc', 'aes192-cbc', 'aes256-cbc', 'arcfour', 'rijndael-cbc@lysator.liu.se'] client mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] server mac:['hmac-md5', 'hmac-sha1', 'umac-64@openssh.com', 'hmac-sha2-256', 'hmac-sha2-512', 'hmac-ripemd160', 'hmac-ripemd160@openssh.com', 'hmac-sha1-96', 'hmac-md5-96'] client compress:['none', 'zlib@openssh.com'] server compress:['none', 'zlib@openssh.com'] client lang:[''] server lang:[''] kex follows?False
DEBUG    paramiko.transport:transport.py:1819 Kex agreed: diffie-hellman-group-exchange-sha256
DEBUG    paramiko.transport:transport.py:1819 HostKey agreed: ssh-rsa
DEBUG    paramiko.transport:transport.py:1819 Cipher agreed: aes128-ctr
DEBUG    paramiko.transport:transport.py:1819 MAC agreed: hmac-sha2-256
DEBUG    paramiko.transport:transport.py:1819 Compression agreed: none
DEBUG    paramiko.transport:transport.py:1819 Got server p (2048 bits)
DEBUG    paramiko.transport:transport.py:1819 kex engine KexGexSHA256 specified hash_algo <built-in function openssl_sha256>
DEBUG    paramiko.transport:transport.py:1819 Switch to new keys ...
DEBUG    paramiko.transport:transport.py:1819 Attempting password auth...
DEBUG    paramiko.transport:transport.py:1819 userauth is OK
INFO     paramiko.transport:transport.py:1819 Authentication (password) successful!
DEBUG    paramiko.transport:channel.py:1212 [chan 0] Max packet in: 32768 bytes
DEBUG    paramiko.transport:channel.py:1212 [chan 0] Max packet out: 32768 bytes
DEBUG    paramiko.transport:transport.py:1819 Secsh channel 0 opened.
DEBUG    paramiko.transport:channel.py:1212 [chan 0] EOF sent (0)
DEBUG    paramiko.transport:channel.py:1212 [chan 0] EOF received (0)
DEBUG    paramiko.transport:transport.py:1819 EOF in transport thread
INFO     root:test_api_all.py:290 sql执行结果：None